version: '3'

services:

  pifs:
    build: ./
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./pifs.php:/app/public/index.php
      - ./cache:/app/public/cache
    environment:
      - 'CONTAINER_TIMEZONE=Australia/Perth'
      - 'APACHE_SERVER_NAME=localhost'
      - 'PHP_DATE_TIMEZONE=Australia\/Perth'
      - 'PHP_ERROR_REPORTING=E_ALL'
      - 'PHP_DISPLAY_ERRORS=On'
      - 'PHP_VARIABLES_ORDER=EGPCS'
      - 'ALLOW_REMOTE=http://,https://'
    #  - 'CACHE_SAVE=1'
    #  - 'CACHE_PATH=cache/'
    #  - 'EMPTY_CACHE_PW=password'
    #  - 'JPG_QUALITY=100'
    #  - 'PNG_QUALITY=0'
    cap_add:
      - SYS_TIME
      - SYS_NICE